# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/detection_dataloader.ipynb.

# %% auto 0
__all__ = ['DetDatasetConfig']

# %% ../../nbs/data/detection_dataloader.ipynb 1
from dataclasses import dataclass
from typing import Tuple, Literal, List, Dict, Union
from pathlib import Path

@dataclass
class DetDatamoduleConfig:
    windows: List[Dict]
    cache_root_path: Union[Path, str]
    centers_to_exclude: List[str]
    annotated_by: str
    scan_annot_type: str
    batch_size: int = 2
    num_workers: int = 4
    pin_memory: bool = True
    shuffle_train: bool = True
    drop_last: bool = True
    patch_size: Tuple[int, int, int] = (128, 128, 128)

@dataclass
class DetDatasetConfig:
    patch_size: Tuple[int, int, int]
    split: Literal["train", "val"]
    centers_to_exclude: List[str]
    windows: List[Dict]
    annotated_by: str
    scan_annot_type: Literal["full_annot", "partial_annot"]
    cache_root_path: Union[Path, str]