# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_layers.ipynb.

# %% auto 0
__all__ = ['nonzero_tuple', 'cat', 'shapes_to_tensor', 'ShapeSpec']

# %% ../nbs/03_layers.ipynb 0
import torch
from typing import List, Optional
from dataclasses import dataclass

def nonzero_tuple(x):

    """
    A 'as_tuple=True' version of torch.nonzero to support torchscript.
    because of https://github.com/pytorch/pytorch/issues/38718
    """
    
    if torch.jit.is_scripting():
        if x.dim() == 0:
            return x.unsqueeze(0).nonzero().unbind(1)
        return x.nonzero().unbind(1)
    else:
        return x.nonzero(as_tuple=True)
    
def cat(tensors: List[torch.Tensor], dim: int = 0):
    """
    Efficient version of torch.cat that avoids a copy if there is only a single element in a list
    """
    assert isinstance(tensors, (list, tuple))
    if len(tensors) == 1:
        return tensors[0]
    return torch.cat(tensors, dim)

def shapes_to_tensor(x: List[int], device: Optional[torch.device] = None) -> torch.Tensor:
    """
    Convert a list of shapes to a torch tensor.
    """
    return torch.as_tensor(x, device=device)

@dataclass
class ShapeSpec:
    
    """
    A simple structure that contains basic shape specification about a tensor.
    It is often used as the auxiliary inputs/outputs of models,
    to complement the lack of shape inference ability among pytorch modules.
    """

    channels: Optional[int] = None
    height: Optional[int] = None
    width: Optional[int] = None
    depth: Optional[int] = None
    stride: Optional[int] = None
