# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/loss/losses.ipynb.

# %% auto 0
__all__ = ['dynamic_sigmoid_focal_loss']

# %% ../../nbs/loss/losses.ipynb 0
import torch
import torch.nn.functional as F


def dynamic_sigmoid_focal_loss(
    inputs: torch.Tensor,
    targets: torch.Tensor,
    alpha: float = 0.25,
    gamma_base: float = 2.0,
    beta: float = 5.0,
    reduction: str = "none",
) -> torch.Tensor:
    """
    Dynamic Focal Loss as described in the paper.

    Args:
        inputs (Tensor): Predicted logits of shape (N, C, ...)
        targets (Tensor): Binary targets of same shape as inputs
        alpha (float): Weighting factor for positive examples
        gamma_base (float): Base gamma value
        beta (float): Dynamic modulation strength
        reduction (str): 'none' | 'mean' | 'sum'

    Returns:
        Tensor: Loss tensor
    """

    # Sigmoid probabilities
    prob = torch.sigmoid(inputs)

    # p_t: probability of the true class
    p_t = prob * targets + (1 - prob) * (1 - targets)

    # Adjusted probability (same as p_t)
    p_adj = p_t

    # Dynamic gamma_i
    gamma = gamma_base + beta * (1.0 - p_adj)

    # Alpha balancing (same as torchvision)
    if alpha >= 0:
        alpha_t = alpha * targets + (1 - alpha) * (1 - targets)
    else:
        alpha_t = 1.0

    # Compute focal modulation term
    focal_weight = (1.0 - p_adj) ** gamma

    # Compute BCE loss
    ce_loss = F.binary_cross_entropy_with_logits(
        inputs, targets, reduction="none"
    )

    # Final loss
    loss = alpha_t * focal_weight * ce_loss

    if reduction == "mean":
        return loss.mean()
    elif reduction == "sum":
        return loss.sum()
    return loss
