# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/data/detection_dataloader.ipynb.

# %% auto 0
__all__ = ['corners_to_cccwhd', 'cccwhd_to_corners']

# %% ../../nbs/data/detection_dataloader.ipynb 3
def corners_to_cccwhd(x0, y0, z0, x1, y1, z1):
    w = x1 - x0
    h = y1 - y0
    d = z1 - z0
    xc = x0 + w / 2
    yc = y0 + h / 2
    zc = z0 + d / 2
    return (xc, yc, zc, w, h, d)

def cccwhd_to_corners(box):
    xc, yc, zc, w, h, d = box
    return (
        xc - w / 2, yc - h / 2, zc - d / 2,
        xc + w / 2, yc + h / 2, zc + d / 2,
    )

